version: "3.8"

services:
  accounts:
    build: ./services/accounts
    ports:
      - "127.0.0.1:8000:5000"
    volumes:
      - ./services/accounts:/app

  transactions:
    build: ./services/transactions
    ports:
      - "5001"

  ui:
    build: ./services/ui
    ports:
      - "127.0.0.1:8001:5002"
    volumes:
      - ./services/ui:/app